In [ ]:
%sql
# create catalog
CREATE CATALOG IF NOT EXISTS nyctaxi_project;

DataFrame[]

In [ ]:
%sql
# create schemas
CREATE SCHEMA IF NOT EXISTS nyctaxi_project.landing;
CREATE SCHEMA IF NOT EXISTS nyctaxi_project.bronze;
CREATE SCHEMA IF NOT EXISTS nyctaxi_project.silver;
CREATE SCHEMA IF NOT EXISTS nyctaxi_project.gold;

DataFrame[]

In [ ]:
%sql
# create volume
CREATE VOLUME IF NOT EXISTS nyctaxi_project.landing.yellow_taxi;

DataFrame[]

In [17]:
dbutils.fs.mkdirs("/Volumes/nyctaxi_project/landing/yellow_taxi/raw_trips")
dbutils.fs.mkdirs("/Volumes/nyctaxi_project/landing/yellow_taxi/lookup_data")

True

In [ ]:
# %sql
# --buCREATE TABLE to store pipeline run logs

# CREATE SCHEMA IF NOT EXISTS nyctaxi_project.audit;
# CREATE TABLE IF NOT EXISTS nyctaxi_project.audit.yellow_taxi_logs(
#     run_id STRING,
#     step_name STRING,
#     layer STRING,
#     source STRING,
#     target_table STRING,
#     status STRING, 
#     error_message STRING,
#     started_at TIMESTAMP,
#     finished_at TIMESTAMP,
#     rows_read BIGINT,
#     rows_written BIGINT,
#     rows_dropped BIGINT,
#     delta_version BIGINT
# );